// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCourses_Back_End.Infrastructure.Data;

#nullable disable

namespace UCourses_Back_End.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214172421_AddCourseProgressTracking")]
    partial class AddCourseProgressTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AI")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.AuthModel.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ADMIN-CONCURRENCY-12345",
                            Email = "admin@ucourses.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@UCOURSES.COM",
                            NormalizedUserName = "SYSTEM_ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEApg0LLktwX8NyeBdwg0ZoL5ZlibZb2GXVgum6NUfBDGZNdVgna2PGAQSWGM6TtJdg==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5f",
                            SecurityStamp = "ADMIN-SECURITY-STAMP-12345",
                            TwoFactorEnabled = false,
                            UserName = "system_admin"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "INSTRUCTOR-CONCURRENCY-12345",
                            Email = "instructor@ucourses.com",
                            EmailConfirmed = true,
                            FirstName = "Main",
                            LastName = "Instructor",
                            LockoutEnabled = false,
                            NormalizedEmail = "INSTRUCTOR@UCOURSES.COM",
                            NormalizedUserName = "MAIN_INSTRUCTOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEGYkccUpGHTwfdA4FBPmLQAomDlnch/RmmjWZIAh5ABhvFC5y7lbrU7jLry5lCt/gQ==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5q",
                            SecurityStamp = "INSTRUCTOR-SECURITY-STAMP-12345",
                            TwoFactorEnabled = false,
                            UserName = "main_instructor"
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STUDENT-CONCURRENCY-12345",
                            Email = "student@ucourses.com",
                            EmailConfirmed = true,
                            FirstName = "Main",
                            LastName = "Student",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@UCOURSES.COM",
                            NormalizedUserName = "MAIN_STUDENT",
                            PasswordHash = "AQAAAAIAAYagAAAAEDcLX8o5AJxGucVj9ZHHkjDZIGzHb8L5tNc2As6sbuWkT1uL9PRGsgMf8VlGG7dN9Q==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5p",
                            SecurityStamp = "STUDENT-SECURITY-STAMP-12345",
                            TwoFactorEnabled = false,
                            UserName = "main_student"
                        });
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.AuthModel.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1c1c1c1-d2d2-4e3e-f4f4-a5a5a5a5a5a5"),
                            CreatedAt = new DateOnly(2024, 1, 1),
                            DepartmentId = new Guid("a1a1a1a1-b2b2-4c3c-d4d4-e5e5e5e5e5e5"),
                            Description = "Complete guide to building web applications with ASP.NET Core",
                            ImageUrl = "/Images/Courses/aspnet-core.jpg",
                            InstructorId = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            Name = "ASP.NET Core Complete Guide",
                            Price = 499.99m,
                            PublicId = "CRS-c1c1c1c1",
                            Status = "Published"
                        },
                        new
                        {
                            Id = new Guid("d2d2d2d2-e3e3-4f4f-a5a5-b6b6b6b6b6b6"),
                            CreatedAt = new DateOnly(2024, 1, 1),
                            DepartmentId = new Guid("b2b2b2b2-c3c3-4d4d-e5e5-f6f6f6f6f6f6"),
                            Description = "Build cross-platform mobile apps with React Native",
                            ImageUrl = "/Images/Courses/react-native.jpg",
                            InstructorId = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            Name = "React Native Masterclass",
                            Price = 599.99m,
                            PublicId = "CRS-d2d2d2d2",
                            Status = "Draft"
                        });
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.CourseProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WatchedDuration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("EnrollmentId", "SectionId")
                        .IsUnique();

                    b.ToTable("CourseProgress");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-b2b2-4c3c-d4d4-e5e5e5e5e5e5"),
                            CreatedAt = new DateOnly(2024, 1, 1),
                            Description = "Learn modern web development technologies",
                            ImageUrl = "/Images/Departments/web-dev.jpg",
                            Name = "Web Development",
                            PublicId = "DEPT-a1a1a1a1"
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-c3c3-4d4d-e5e5-f6f6f6f6f6f6"),
                            CreatedAt = new DateOnly(2024, 1, 1),
                            Description = "Master mobile app development",
                            ImageUrl = "/Images/Departments/mobile-dev.jpg",
                            Name = "Mobile Development",
                            PublicId = "DEPT-b2b2b2b2"
                        });
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("CourseId", "StudentId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-b2b2-4c3c-d4d4-111111111111"),
                            CourseId = new Guid("c1c1c1c1-d2d2-4e3e-f4f4-a5a5a5a5a5a5"),
                            CreatedAt = new DateOnly(2024, 1, 1),
                            PublicId = "ENRL-a1a1a1a1",
                            StudentId = new Guid("f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c")
                        });
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("EndAt")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartAt")
                        .HasColumnType("time");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1e1e1e1-f2f2-4a3a-b4b4-c5c5c5c5c5c5"),
                            CourseId = new Guid("c1c1c1c1-d2d2-4e3e-f4f4-a5a5a5a5a5a5"),
                            CreatedAt = new DateOnly(2024, 1, 1),
                            DayOfWeek = 1,
                            Description = "Getting started with ASP.NET Core framework",
                            EndAt = new TimeOnly(12, 0, 0),
                            Name = "Introduction to ASP.NET Core",
                            PdfUrl = "/PDFs/Sections/aspnet-intro.pdf",
                            PublicId = "SEC-e1e1e1e1",
                            StartAt = new TimeOnly(10, 0, 0),
                            VideoUrl = "/Videos/Sections/aspnet-intro.mp4"
                        },
                        new
                        {
                            Id = new Guid("f2f2f2f2-a3a3-4b4b-c5c5-d6d6d6d6d6d6"),
                            CourseId = new Guid("d2d2d2d2-e3e3-4f4f-a5a5-b6b6b6b6b6b6"),
                            CreatedAt = new DateOnly(2024, 1, 1),
                            DayOfWeek = 2,
                            Description = "Learn the fundamentals of React Native",
                            EndAt = new TimeOnly(16, 0, 0),
                            Name = "React Native Basics",
                            PublicId = "SEC-f2f2f2f2",
                            StartAt = new TimeOnly(14, 0, 0),
                            VideoUrl = "/Videos/Sections/react-native-basics.mp4"
                        });
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.Users.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            AppUserId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            CreatedAt = new DateOnly(2024, 1, 1),
                            PublicId = "ADM-d4e5f6a7"
                        });
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.Users.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndContract")
                        .HasColumnType("date");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            AppUserId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            CreatedAt = new DateOnly(2024, 1, 1),
                            EndContract = new DateOnly(2025, 1, 1),
                            IsApproved = true,
                            PublicId = "INST-e5f6a7b8",
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.Users.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c"),
                            AppUserId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            CreatedAt = new DateOnly(2024, 1, 1),
                            PublicId = "STUD-f6a7b8c9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.AuthModel.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.AuthModel.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCourses_Back_End.Core.Entites.AuthModel.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.AuthModel.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.AuthModel.RefreshToken", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.AuthModel.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Course", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.CoreModels.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UCourses_Back_End.Core.Entites.Users.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.CourseProgress", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.CoreModels.Enrollment", "Enrollment")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCourses_Back_End.Core.Entites.CoreModels.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Enrollment", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.CoreModels.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UCourses_Back_End.Core.Entites.Users.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Section", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.CoreModels.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.Users.Admin", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.AuthModel.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("UCourses_Back_End.Core.Entites.Users.Admin", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.Users.Instructor", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.AuthModel.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("UCourses_Back_End.Core.Entites.Users.Instructor", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCourses_Back_End.Core.Entites.CoreModels.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.Users.Student", b =>
                {
                    b.HasOne("UCourses_Back_End.Core.Entites.AuthModel.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("UCourses_Back_End.Core.Entites.Users.Student", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.AuthModel.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.CoreModels.Enrollment", b =>
                {
                    b.Navigation("ProgressRecords");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.Users.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("UCourses_Back_End.Core.Entites.Users.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
